### ISSUE TITLE
GTCE Splitting Point

### ISSUE THREAD

**Issue by Chocohead** [TrilexLabs/GT5-Unofficial#1]
GTCE continued from the same Git project as this did, which is not obvious as Github doesn't show it as a fork. If you go back far enough in the GTCE history you'll see the 1.12 and 1.10 commits this has, and even further back to the 1.7 code. Most if not all of the actual code from back then is likely gone from GTCE now, but it also means that the end of this project is technically already GTCE:

This [current head](https://github.com/TrilexLabs/GT5-Unofficial/commits/1.12.2) is equivalent to [this position](https://github.com/GregTechCE/GregTech/commits/master?after=4781a3f7025d1f7865c73d1be12d476d4ce7c5f6+511) in GTCE. Thus this is basically 511 commits behind where GTCE is, but is otherwise an identical code base. Hash is the same for both too: [`3d56bf120673a7a9f47769681cfbc8feaec889ab`](https://github.com/TrilexLabs/GT5-Unofficial/commit/3d56bf120673a7a9f47769681cfbc8feaec889ab).

Walking back further, there is no exact GTCE started here point as far as I can tell. There is however the signs of where the big changed started. [`acf337406a385a32f6853c3716fb3e86fa0c0978`](https://github.com/TrilexLabs/GT5-Unofficial/commit/acf337406a385a32f6853c3716fb3e86fa0c0978) is the final commit before the rewriting started, the commit immediately after ([`a77626c5a011a4833302d8760c7d4cb44712e032`](https://github.com/TrilexLabs/GT5-Unofficial/commit/a77626c5a011a4833302d8760c7d4cb44712e032)) starts removing big chunks like the old 1.7 style rendering and using `byte` as a facing parameter when 1.8 added `EnumFacing`. This is around 10 commits after the final non-GTCE version of 5.10.41 was merged in (which I did in Blood-Asp/GT5-Unofficial#1021), so whilst that will be a few commits old itself, means that is clearly a lower bound for GTCE beginning. You can see all this playing out [210 commits behind head](https://github.com/TrilexLabs/GT5-Unofficial/commits/1.12.2?after=3d56bf120673a7a9f47769681cfbc8feaec889ab+210), going forward you see merges referencing branch names like `rewrite`.

Whilst I would be weary of whether starting from 211 commits back from where this is already (ie another 511 commits behind GTCE right now) is a good idea, that is the range GTCE has existed in. The 722 commits will have removed some of the age of the codebase and additional dodgy decompiled lines, but cutting that out from gameplay changes won't be too easy when there are commits touching 2000+ files in one go.

**Comment by trilexcom** [comment]
so start from 211 than go forward

**Comment by Chocohead** [comment]
Start a new branch from `acf337406a385a32f6853c3716fb3e86fa0c0978`, then switch that one to be the main one.

**Comment by trilexcom** [comment]
ok

**Comment by trilexcom** [comment]
thank you bro
